### ISSUE TITLE
fall back to system fonts for missing characters, like math characters

### ISSUE THREAD

**Issue by odanoburu** [mbutterick/quad#12]
I know `quad` is not supposed to replace latex, but I do need some math characters for  code sometimes :P

```agda
excl-middl→¬¬-elim : ∀ {A : Set} → A ⊎ ¬ A → (¬ ¬ A → A)
excl-middl→¬¬-elim (inj₁ a) = λ ¬¬a → a
excl-middl→¬¬-elim (inj₂ ¬a) = λ ¬¬a → ⊥-elim (¬¬a ¬a)
```

rendered as

![image](https://user-images.githubusercontent.com/19347395/57896067-4186ff00-7825-11e9-9b9f-e51b771a86d2.png)

ps: drracket seems to handle both emoji and math, but I imagine they have that taken care of by some underlying library..

**Comment by mbutterick** [comment]
I don’t to rely on system fonts because they’re not portable. Is there another option for math coverage? Maybe the STIX fonts?

**Comment by mbutterick** [comment]
I used the Noto Math font.

![Screen Shot 2019-05-17 at 12 30 46 AM](https://user-images.githubusercontent.com/1425051/57910932-4d7dbb80-783b-11e9-8398-85fbf399b7ac.gif)
