### ISSUE TITLE
The docs aren't working

### ISSUE THREAD

**Issue by oransimhony** [mbutterick/quad#15]
I tried to go to the docs from the link in the README [https://docs.racket-lang.org/quad](https://docs.racket-lang.org/quad) but received the following error:

>  Page Not Found
> ((uncaught-exception-handler)    (*(+(*)(*(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*))))(+(*)(*)(*)(*)))) uncaught exception: 404

This might happen since the build currently fails on [here](https://pkgs.racket-lang.org/package/quad)

Loved your tutorials on Beautiful Racket and they helped me get familiar with this great language :)

**Comment by mbutterick** [comment]
Sorry, I broke the build yesterday. If you install `quad` the docs will build locally. Otherwise the `docs` server will show the fixed docs in a few hours.

**Comment by mbutterick** [comment]
The docs have [now reappeared](https://docs.racket-lang.org/quad/).
