### ISSUE TITLE
The docs for quad aren't available at docs.racket-lang.org

### ISSUE THREAD

**Issue by jackfirth** [mbutterick/quad#2]
I'd like to read more about quad, but there's no docs for it at docs.racket-lang.org. This seems to be because the [quad](https://pkgs.racket-lang.org/package/quad) package is [failing to build](https://pkg-build.racket-lang.org/server/built/fail/quad.txt) in the package build server.

**Comment by mbutterick** [comment]
Here's a [sample from the Racket docs](https://github.com/mbutterick/quad/files/3000024/docs.pdf) that’s been converted to Markdown and then rendered to PDF with Quad. There are a few more things I’d like to add before putting up a new docs / demo page, like hyphenation and full justification. Another 30 days or so.

**Comment by mbutterick** [comment]
BTW there’s no LaTeX or even `racket/draw` used here. The PDF is built from a Racket source file (that contains the Markdown, interpreted by a special `#lang quad/markdown` dialect) and a folder of fonts. The system is in four layers: the top layer is Quad per se, which does the layout; this sits atop a PDF compiler; this sits atop a font-parsing library (which relies on Harfbuzz for shaping and measurement); this sits atop a binary codec library.

**Comment by mbutterick** [comment]
33 days later: the demo is ready. [Docs are here](http://docs.racket-lang.org/quad) but won’t refresh till tomorrow.

**Comment by jackfirth** [comment]
Looking forward to it! Also the native Racket font parsing and PDF compiler libraries are awesome!
