### ISSUE TITLE
view-result fails when PDF path contains spaces

### ISSUE THREAD

**Issue by tchajed** [mbutterick/quad#24]
The system command view-result runs doesn't use a quote around the path, so a path with a space doesn't work correctly. I think you just need quotes around `~a` in the following code:

https://github.com/mbutterick/quad/blob/154dac901c92f667d5875a992bf06b61b653d6a3/quadwriter/lang-helper.rkt#L59-L61.

**Comment by mbutterick** [comment]
Thanks!
