### ISSUE TITLE
Install issues on Windows / WSL

### ISSUE THREAD

**Issue by oldmankit** [mbutterick/quad#43]
I'm stoked to try out Quad as I'm at the start of a new Pollen project that requires PDF output. I tried to get some highly elegant functions borrowed from [TFL](https://docs.racket-lang.org/pollen-tfl/_pollen_rkt_.html#%28def._%28%28lib._pollen-tfl%2Fpollen..rkt%29._make-list-function%29%29) (such as `make-list-function`) to work in terms of Latex output, which was difficult, and I thought that Quad will probably be a more natural fit for Pollen source code, given that it's based on Q-expressions, which I think must be more similar to S-expressions than is the language of Latex. If I can avoid the whole Latex route it would be a **gift**.

## Installing in Windows

I had trouble installing Quad. At the end of the install it said a package couldn't be found:

`ffi-lib: couldn't open "C:\\Program Files\\Racket\\lib\\libfreetype-6.dll" (The specified module could not be found.; errid=126)`

There were also several warnings which I've stored in a [gist](https://gist.github.com/oldmankit/3bce65b9d8a0abb8b82d5114ab270d6c#file-gistfile1-txt).

To see if Quad was going to work anyway, I tried processing the [test.rkt](https://docs.racket-lang.org/quad/index.html?q=quad#%28part._.Quadwriter___.Markdown%29) file from the Quad docs. It did not run, but again complained that libfreetype cannot be found.

## Installing in WSL

I have read of a Pollen user who couldn't install Joel Dueck's try-pollen say that a similar issue (though with a different package) is [solved](https://github.com/otherjoel/try-pollen/issues/7) by not using Racket in Windows, but in the Windows Subsystem for Linux. I tried this, and the installer no-longer complained about a lack of libfreetype. However, I noticed several messages during install for the package xenomorph, seeing `bad syntax` many times. The install completed with warnings (see [this gist](https://gist.github.com/oldmankit/89b8be41b23deeeac2c2f7e8327616a9#file-gistfile1-txt)).

On testing it with the same `test.rkt` file, the following is returned:

```
racket test.rkt
/home/me/.racket/6.11/pkgs/xenomorph/xenomorph/int.rkt:76:6: for/fold/derived: bad syntax
  in: (for/fold/derived (for/fold ((bs null) (val (exact-if-possible val)) #:result (apply bytes ((if (eq? @endian (quote be)) values reverse) bs))) ((i (in-range @size))) (values (cons (bitwise-and val 255) bs) (arithmetic-shift val -8))) ((bs null) (val (ex...  
```

I have run `raco pkg update --update-deps quad` to see that no updates are available.

Sorry for the length of this issue. I would be happy to get this working either in Windows or WSL. I feel that WSL may actually be more pain-free in the long-term, but any working version of Quad would be great.

**Comment by mbutterick** [comment]
I’ll take a look. As I’ve indicated elsewhere I’m a bit of a Windows rube but these errors should be enough to muddle through.

**Comment by oldmankit** [comment]
Thank you. Please let me know if I can do anything to help.

**Comment by mbutterick** [comment]
Oh, I see the problem. 6.11 is too old. I think 6.12 will suffice. But I only test against 7.1 and above.

**Comment by oldmankit** [comment]
Yep, that's it. It's working now I've upgraded. I didn't know that the default Ubuntu repository was so far out of date.

The test file is now working in WSL, which is great. Thank you!
