### ISSUE TITLE
switch to MIT license

### ISSUE THREAD

**Issue by mbutterick** [mbutterick/quad#47]
@odanoburu 

Consistent with [Racket’s overall relicensing](https://blog.racket-lang.org/2019/11/completing-racket-s-relicensing-effort.html) from LGPL to Apache+MIT, I’d like to move Quad from LGPL to MIT.

Because the MIT license is more permissive, this requires the assent of you, the esteemed contributors.

If you agree, please post a message saying so, e.g. — "I hereby relicense my contributions to Quad under the MIT license."

On January 1, if you have not agreed to the relicensing, I will remove your code. Thanks.

**Comment by odanoburu** [comment]
I hereby relicense my contributions to quad under the MIT license.

**Comment by mbutterick** [comment]
Oops — overzealous caution. This repo was already under MIT 🤦‍♂ Thanks!
