### ISSUE TITLE
Help with Pollen Lists

### ISSUE THREAD

**Issue by oldmankit** [mbutterick/quad#48]
I'd love to get ordered and unordered lists working with Quad, from Pollen source code which separates list items by three new lines (i.e., no need for `li` tags). Here's what I have.

Typography for Lawyers there is a neat function for detecting list items:

```racket
(define (detect-list-items elems)
  (define elems-merged (merge-newlines elems))
  (define (list-item-break? elem)
    (define list-item-separator-pattern (regexp "\n\n\n+"))
    (and (string? elem) (regexp-match list-item-separator-pattern elem)))
  ; Make list-of-li-elems by splitting the merged elements at \n\n\n+
  (define list-of-li-elems (filter-split elems-merged list-item-break?))
  list-of-li-elems)
```

In Quadwriter there are some functions which seem to do the hard work of making lists:

```racket
; Quadwriter Lists
(define (list-base attrs exprs [bullet-val #f])
  (define bullet-space-factor 2.5)
  (define em (dict-ref attrs :font-size default-font-size))
  (define bullet-indent (* bullet-space-factor em))
  (qexpr (cons (list :inset-left (number->string bullet-indent)) attrs)
         (add-between
          (for/list ([(expr idx) (in-indexed exprs)]
                     #:when (txexpr? expr))
                    (list* (get-tag expr) (cons (list :list-index (or bullet-val (format "~a" (add1 idx)))) (get-attrs expr)) (get-elements expr)))
          para-break)))

(define bullet-quad '(q ((special "bullet"))))

(define-tag-function (ol attrs exprs) (list-base attrs exprs))
(define-tag-function (ul attrs exprs) (list-base attrs exprs "•"))
(define-tag-function (li attrs exprs)
  (define new-bullet-quad (match exprs
                            [(cons (txexpr _ attrs _) _)
                             (match bullet-quad
                               [(txexpr tag battrs elems)
                                (define new-attrs
                                  (hash->attrs
                                   (copy-block-attrs (attrs->hash attrs) (attrs->hash battrs))))
                                (txexpr tag new-attrs elems)])]
                            [_ bullet-quad]))
  (qexpr attrs (cons new-bullet-quad exprs)))
```

I'm having some trouble putting these together. Here's what I've got:

```racket
(define (bullet-list . elems)
    (ul (map li (detect-list-items elems))))
```

The `detect-list-items` function seems to be doing its job perfectly, returning a list of each list item. However I'm not passing these to `ul` or `li` correctly, as when I compare the output from this to what is generated by Quadwriter for a markdown list they're rather different. Here is a sample of what Quadwriter produces:

```racket
(q
    ((inset-left "30.0"))
    (q
     ((list-index "•"))
     (q ((special "bullet")))
     "List item one")
    (q ((break "para")))

    (q
     ((list-index "•"))
     (q ((special "bullet")))
     "List item two"))
    (q ((break "para"))
    )
```

However with my `bullet-list` function it's coming out a bit garbled, like this:

```racket
'(q
  ((inset-left "30.0")
    (q ("Item one.") 
      (q ((special "bullet"))))
    (q ("Item two.")
      (q ((special "bullet"))))))
```

The list index character has got lost along the way, and it also doesn't compile correctly ( 'contract violation', expected `txexpr-elements?`).

I'm very grateful for any help, as I've spent a good day knocking my head against how to accomplish this.

**Comment by mbutterick** [comment]
`define-tag-function` is doing some magic to appear to be a two-arity function. But when you use it in a document, it’s actually a variable-arity function. So usually you need to `apply` these functions rather than just call them directly, so you unroll the trailing list of x-expressions.

AFAICT your `bullet-list` is correct, except it needs to use `apply` with `ul` and `li`:

```racket
#lang racket
(require quadwriter/tags pollen/decode sugar/list rackunit)

(define (detect-list-items elems)
  (define elems-merged (merge-newlines elems))
  (define (list-item-break? elem)
    (define list-item-separator-pattern (regexp "\n\n\n+"))
    (and (string? elem) (regexp-match list-item-separator-pattern elem)))
  ; Make list-of-li-elems by splitting the merged elements at \n\n\n+
  (define list-of-li-elems (filter-split elems-merged list-item-break?))
  list-of-li-elems)

(define (bullet-list . elems)
  (apply ul (map (curry apply li) (detect-list-items elems))))

(check-equal?
 (ul (li "hello") (li "world"))
 (bullet-list "hello" "\n\n\n" "world"))
```

**Comment by oldmankit** [comment]
I'm so grateful for your help, @mbutterick . It's good to see that I was on the right track, but I think getting to `(curry apply li)` would've taken me a really long time to get to, even with all the perseverance in the world.

Since getting this to work, I've been able to adapt many of the functions in Quadwriter to work with my existing tags. It's exciting to begin to see some pdf output from Pollen source.

I have one question which is still niggling. In the [TFL docs](https://docs.racket-lang.org/pollen-tfl/_pollen_rkt_.html#%28def._%28%28lib._pollen-tfl%2Fpollen..rkt%29._make-list-function%29%29), `bullet-list` is defined like this:

`(define bullet-list (make-list-function 'ul))`

This calls `make-list-function` with the argument `'ul`. What I don't understand is why there is no rest argument. How does the actual content of the list ever make it through to `make-list-function`? As far as I can see it just gets in behind the scenes somehow.

Here is that `make-list-function`:

```racket
(define (make-list-function tag [attrs empty])
(λ args (list* tag attrs (detect-list-items args))))
```

There is only one parameter, `tag`, and optional `attrs`, but no rest parameter. How is it that `args` can be defined within the lamda function when it's no matching parameter in the parent function?

**Comment by mbutterick** [comment]
> getting to (curry apply li) would've taken me a really long time

There’s no magic to `curry`. These are equivalent:

```
(define (bullet-list . elems)
  (apply ul (map (λ (xs) (apply li xs)) (detect-list-items elems)))) 
```

```
(define (bullet-list . elems)
  (apply ul (for/list ([item-elems (in-list (detect-list-items elems))])
              (apply li item-elems))))
```

> This calls make-list-function with the argument 'ul. What I don't understand is why there is no rest argument.

Look carefully at `make-list-function`. When you call it with a tag and optional attrs, you get back another function that is variadic (that is, takes a rest argument — this is the meaning of `(λ args ···)`) We could refactor it to be explicit:

```
(define (make-list-function tag [attrs empty])
  (define (my-list-function . args)
    (list* tag attrs (detect-list-items args)))
  my-list-function)
```

Racket also supports “curried” notation like so, which means the same thing:

```
(define ((make-list-function tag [attrs empty]) . args)
  (list* tag attrs (detect-list-items args)))
```

Use whichever style you like.

**Comment by otherjoel** [comment]
> It's good to see that I was on the right track, but I think getting to `(curry apply li)` would've taken me a really long time to get to, even with all the perseverance in the world.

Just want to add that I feel I can identify with this somewhat. I came to a Butterick DSL wanting to get certain things done without having any LISP or FP background, and found myself asking the same kinds of questions. 

If you have any familiarity with a LISP, these things come pretty naturally. If not — you’re right, perseverance alone isn't going to get you there. Like me you'll progress by asking one-off questions and get used to feeling a little stupid every time you get the answer, until you realize it is all clicking into place.

I've long thought that _maybe_ a more ego-friendly? honest? on-boarding experience for DSLs like Quad and Pollen (that appeal to lots of people who otherwise have no FP background) would exhort newcomers to just read all of [_How to Design Programs_](https://www.htdp.org/2019-02-24/index.html)  and then come back and start the tutorials. (I still haven't actually read the whole thing.) But I don't mind feeling a little stupid as long as I'm actually learning something useful, and plunging into Pollen blind turned out to be a great gateway into fundamental Racket/FP concepts.

**Comment by mbutterick** [comment]
For my part, I wouldn’t want anyone to feel they need to read a 500-page textbook to use my software. For instance, the [Beautiful Racket explainers](https://beautifulracket.com/#explainers) are meant, in part, to serve as the bullet-train intro to various topics. (Though true — I don’t link to them from the Pollen or Quad docs. Maybe I should?)

The challenge for me as a writer of docs is introducing the material in a way that’s gentle for newcomers but not boring for experienced programmers. Given the thoroughness of the rest of the Racket docs, I have to hope that when someone hits a stumbling block, they will click over and fortify their knowledge.

Still, I don’t get complaints about the Pollen tutorials these days (in terms of concepts insufficiently explained) — I take that as a good sign. In this case, @oldmankit is trying to adapt a tutorial project to his own needs, which necessarily means encountering some rough edges I can’t plan for.

Also, today Quad is **far** less stable & mature than Pollen. A warning to that effect appears in the first paragraph of the docs. Though it’s not my goal to waste anyone’s time, the learning curve is going to be pretty steep for a while to come. Use at your own risk, etc.

**Comment by mbutterick** [comment]
PS. I do make some calculation — not to exclude people, exactly — but to attract a type of user to Pollen who likes to hack around a bit. You know: like me. This is why, for instance, I don’t ship Pollen with ready-made CSS & HTML templates. I could. But then I would be awash in users who want readymade solutions. That’s a legit audience. But not one I can support for free.

**Comment by oldmankit** [comment]
> asking one-off questions and get used to feeling a little stupid every time you get the answer, until you realize it is all clicking into place.

Yes, I very much feel like that. I think the problem for me has been that for several years I became exposed to programming without really having much understanding of it, and developed (and I’m quoting now from the preface of ‘How to Design Programs’) a “tinker until it works” approach. This has massively slowed down my progress. Recently I’ve decided to invest the time to try to understand things well, and two things that have inspired me to do this are the brilliant answers I’ve received for my piecemeal Pollen questions, and also the elegance of code I’ve seen in TFL. The other main motivator is I can really see programming becoming a more important part of my life, and I’m sick of being bad at it. I spent a couple of years learning calligraphy and if I could bring the same patience and care to programming, I think I’d be on to a winner.

**Comment by oldmankit** [comment]
As for my code questions, I think it would be right to say that the original version of `make-list-function` is a higher-order function, itself returning a function. I’ve studied that before but it turns out I hadn’t fully grasped the implications for arguments. 

And thank you again MB for giving two alternatives to `(curry apply li)`. That’s made it completely clear.

**Comment by mbutterick** [comment]
> developed (and I’m quoting now from the preface of ‘How to Design Programs’) a “tinker until it works” approach. This has massively slowed down my progress

“Tinkering” is a legitimate way of figuring things out in programming. For me, even after years of programming, there are still long bouts of tinkering (and concomitant frustration). Programming is a way of rendering algorithmic ideas into code. But it’s also a way of learning / discovering those ideas in the first place (and then iteratively refining them into viable solutions). 

Since you’re new to programming I also recommend reading (whatever you can of) [SICP](https://mitpress.mit.edu/sites/default/files/sicp/full-text/sicp/book/book.html). This is the book that made me excited about the possibilities of Lisp languages.

**Comment by oldmankit** [comment]
> “Tinkering” is a legitimate way of figuring things out in programming.

I think for me it slowed down my progress because I would copy and paste code and tinker until it did what I wanted, using the absolute minimum of understanding required. So understanding only came in tiny little chunks, which were really quite expensive chunks when considering how much tinkering was required to get them. When I took my first programming course last year it was really wonderful to get so much understanding so quickly.

> But it’s also a way of learning / discovering those ideas in the first place (and then iteratively refining them into viable solutions).

I feel similarly about writing (words for people, not for computers). The process of writing is often the catalyst to really getting a good understanding of something.

Thanks for the book recommendation!
