### ISSUE TITLE
lang-helper.rkt:82:30: in-string: contract violation when using lists

### ISSUE THREAD

**Issue by ergl** [mbutterick/quad#49]
Hi! I just downloaded quad and was following the examples from the documentation in DrRacket, when I hit this error. Having a single file with just:

```
#lang quadwriter/markup
◊ul{}
```

Produces the following error in DrRacket:

```
quadwriter: hyphenate: 0ms
./Library/Racket/7.5/pkgs/quad/quadwriter/lang-helper.rkt:82:30: in-string: contract violation
  expected: string
  given: #<procedure:pair?>
quadwriter: setup-qs: 5ms
```

Racket version: 7.5
macOS Mojave 10.14.6
quad `011b03d81a6c752669f` installed with `raco`

Any of the examples in the docs containing lists (be them in markdown on in markup) will cause the error too.

**Comment by mbutterick** [comment]
Thanks!
