### ISSUE TITLE
no output in racket-mode

### ISSUE THREAD

**Issue by odanoburu** [mbutterick/quad#5]
**disclaimer**: I'm sorry if this is not a `quad` issue, but a `racket-mode` issue!

currently writing a small document in emacs using racket-mode and  `#lang quadwriter/markdown` in linux fedora 29.

running the document in the REPL I get no PDF output and no logging (which work alright on DrRacket). if I run `doc`, it does show me the corresponding Q-expression. 

(I of course understand if it's too early to support anything other than DrRacket!)

**Comment by mbutterick** [comment]
Does it work on the command line?

**Comment by odanoburu** [comment]
yes it does!

**Comment by mbutterick** [comment]
I don’t know anything about `racket-mode`, sorry. If it works in DrRacket and the command line, it seems like it should work in `racket-mode` too.

**Comment by mbutterick** [comment]
Closing this because it doesn’t seem to be `quad`’s fault.
