### ISSUE TITLE
Thai script not displayed correctly

### ISSUE THREAD

**Issue by sorawee** [mbutterick/quad#55]
Consider:

```
#lang quadwriter/markup

#:font-family "Sarabun"

สวัสดีชาวโลก
```

where the `Sarabun` directory/zip can be downloaded from https://fonts.google.com/specimen/Sarabun.

The result of the pdf is 

<img width="553" alt="Screen Shot 2020-02-18 at 14 27 27" src="https://user-images.githubusercontent.com/9099577/74783574-d27a8300-525a-11ea-99dc-a81554b5a11e.png">

which shows "สวัสดีชาวโ" instead of "สวัสดีชาวโลก" (the last two characters are missing).

**Comment by sorawee** [comment]
My hypothesis is that "ั" "ี" that appear in "วั" and "ดี" stack on top of the previous character, so two characters are missing.

I tested further by trying:

```
#lang quadwriter/markup

#:font-family "Sarabun"

ฉันสู้ตาย
```

In the above one, there's "ั", "ั", and "ู" (the last two attach to the top and bottom of "ส" in "สู้"). The result is that three characters are missing, which matches the prediction.

**Comment by oldmankit** [comment]
Just to provide a bit of context, in Thai script any consonant can have diacritics (vowels and tone markers) stacked above and below it. There is one position below any consonant, and two above (I think that's the limit, but haven't checked). This [stackexchange post](https://graphicdesign.stackexchange.com/questions/116552/how-do-i-get-thai-diacritics-to-display-correctly-in-indesign-cs6) provides visual examples.

@sorawee 's hypothesis is that for every diacritic that is used, there is corresponding number of characters missing from the Quad output.

I tried to do some of my own tests but I'm not able to get any sensible output. My pdf looks like this:

![image](https://user-images.githubusercontent.com/4979371/74790580-9262e100-52ea-11ea-9efd-285eab586ed1.png)

**Comment by sorawee** [comment]
@oldmankit you need to create a directory named "fonts" and extract the font files in a subdirectory "Sarabun" to get the font working.

**Comment by mbutterick** [comment]
Fixed in https://github.com/mbutterick/fontland/commit/5dacd2def4f649011e2efd0e8c49a538612bbfd0
Tested in https://github.com/mbutterick/pitfall/commit/dbaf0c160f96330de9476d100ae938e085167fc8

(Meaning, you will have to update `fontland` to get the fix)

**Comment by mbutterick** [comment]
![Screen Shot 2020-02-19 at Feb 19  1 46 58 PM](https://user-images.githubusercontent.com/1425051/74879603-53e71980-531e-11ea-9c9b-f89d762beeb8.gif)

**Comment by oldmankit** [comment]
@sorawee Thanks very much for your help: yes, that fixes it.
