### ISSUE TITLE
"Combining Quadwriter with Pollen" code samples do not produce the intended PDF

### ISSUE THREAD

**Issue by arnaudchenyensu** [mbutterick/quad#61]
When using the code samples of the section [Combining Quadwriter with Pollen](https://docs.racket-lang.org/quad/#%28part._.Combining_.Quadwriter_with_.Pollen%29), the PDF produced is

```
likes fancy sauce..

Dale hates fancy sauce.
```

rather than the expected:

```
Brennan likes fancy sauce.

Dale hates fancy sauce.
```

**Comment by mbutterick** [comment]
Thanks!
