### ISSUE TITLE
Anchors don't seem to work

### ISSUE THREAD

**Issue by arnaudchenyensu** [mbutterick/quad#62]
With this code:

```
#lang quadwriter
'(q ((draw-debug "true") (anchor-from-parent "n") (anchor-to "n")) "Just a text")
```

I'm expecting the text to be centered to the top of the page, but here's what I'm getting:

![Screenshot from 2020-05-15 23-08-45](https://user-images.githubusercontent.com/1472712/82054147-d30fa200-9701-11ea-90e5-5915388aed6d.png)

Am I doing it wrong?

**Comment by mbutterick** [comment]
No, they don’t really work yet. For now, IIRC only drawing objects like `line` and `text` can be positioned:

```
#lang quadwriter
'(q ((draw-debug "true"))
    "body text"
    (text ((anchor-from-parent "n")
           (parent "page[this]")
           (anchor-to "n")
           (string "Just a text"))))
```

**Comment by arnaudchenyensu** [comment]
Does it mean that images also can't be positioned?

**Comment by mbutterick** [comment]
Maybe someday. But not today.

**Comment by arnaudchenyensu** [comment]
Ok, thank you very much for your help.
