### ISSUE TITLE
spacing issues

### ISSUE THREAD

**Issue by odanoburu** [mbutterick/quad#64]
an image describing the problem:

![image](https://user-images.githubusercontent.com/19347395/86491961-c93e0e80-bd42-11ea-8ebc-0ede9373479a.png)

(I expect a space to be inserted between linebreaks not forming a paragraph)

**Comment by mbutterick** [comment]
Thanks! I agree that the current behavior is wrong. But I think one newline should be interpreted as a line break (not a word space), since that’s more consistent with the behavior that two newlines are interpreted as a paragraph break.

**Comment by odanoburu** [comment]
> I think one newline should be interpreted as a line break (not a word space)

I see! I'm not sure I said what I mean, I expected behaviour similar to that of latex or even markdown, where if you want a linebreak you have a command for that, and newlines are just for preventing lines in the editor becoming too long

thank you for the fast fixes!

**Comment by mbutterick** [comment]
I see. Maybe that’s the better idea. Let me think about it a little more.

**Comment by odanoburu** [comment]
sure! I can work with both, on Emacs I just enabled `visual-lines-mode` to have virtual linebreaks automatically included. not sure how long lines would display on DrRacket if there's no such alternative, though. I had been calling `◊br{}` on the document to insert linebreaks too.

**Comment by mbutterick** [comment]
It seems that `quadwriter/markdown` does not automatically insert linebreaks, so probably it makes sense that `quadwriter/markup` is consistent. Enjoy.
