### ISSUE TITLE
mention q-expression escape in quadwriter/markup

### ISSUE THREAD

**Issue by odanoburu** [mbutterick/quad#65]
I just realised (maybe I knew it at some point) that you can ‘escape’ to q-expressions while using `quadwriter/markup`, and think that it would be useful to include this in the manual at https://docs.racket-lang.org/quad/#%28part._.Quadwriter___markup%29

I can make a PR if you agree!

(I found about this while embedding an image, I didn't manage to set the width using the `img` element, so I used a q-expression and it worked beautifully)

**Comment by mbutterick** [comment]
I’m don't totally remember what you mean, so I look forward to reading the new documentation :wink:
